SIMULATOR__Logger_Level: DEBUG
SIMULATOR__MqttBroker_Cert_CA: ""
SIMULATOR__MqttBroker_Cert_Crt: ""
SIMULATOR__MqttBroker_Cert_Key: ""
SIMULATOR__MqttBroker_Keepalive: "3000000000"
SIMULATOR__MqttBroker_QoS: ONCE
SIMULATOR__MqttBroker_RetainPublish: "false"
SIMULATOR__MqttBroker_Retry_Interval: "3000000000"
SIMULATOR__MqttBroker_Retry_Repeats: "3"
SIMULATOR__MqttBroker_Server: tcp://127.0.0.1:1883
SIMULATOR__MqttBroker_Timeout: "10000000000"
