version: "3.6"

services:
  mqtt:
    image: eclipse-mosquitto:1.6.15
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./build/mqtt-dev:/mosquitto/data

  postgres:
    image: postgres:13
    restart: always
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements",
        "-cstats_temp_directory=/tmp"
      ]
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "passwd"
      POSTGRES_DB: "pebble"
    volumes:
      - ./build/postgres-dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./build/prometheus-dev:/prometheus"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "./build/grafana-dev:/var/lib/grafana"

  pebble-sequencer:
    image: ghcr.io/machinefi/pebble-sequencer:latest
    container_name: pebble-sequencer
    platform: linux/amd64
    restart: always
    depends_on:
      - "postgres"
      - "mqtt"
    command:
      [ "run" ]
    ports:
      - "80:80"
    environment:
      PEBBLE_SEQUENCER__Blockchain_PersistPath: /data/pebbletx
      PEBBLE_SEQUENCER__Database_Endpoint: postgres://test:passwd@postgres:5432/pebble?sslmode=disable
      PEBBLE_SEQUENCER__MqttBroker_Server: tcp://mqtt:1883
      PEBBLE_SEQUENCER__ProjectID: 100
      PEBBLE_SEQUENCER__ProjectVersion: v0.0.1
      PEBBLE_SEQUENCER__Blockchain_Network: IOTX_TESTNET
    volumes:
      - ./build/tx-dev:/data

