version: "3.6"

services:
  mqtt:
    image: eclipse-mosquitto:1.6.15
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./build/dep/mqtt:/mosquitto/data

  postgres:
    image: postgres:13
    restart: always
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements",
        "-cstats_temp_directory=/tmp"
      ]
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "passwd"
      POSTGRES_DB: "pebble"
    volumes:
      - ./build/dep/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  clickhouse:
    image: yandex/clickhouse-server:latest
    platform: linux/amd64
    container_name: clickhouse
    ports:
      - "8123:8123"  # http
      - "9000:9000"  # tcp
    volumes:
      - ./build/dep/clickhouse:/var/lib/clickhouse
