REPLICATION_MONITOR__Alert_Env: ""
REPLICATION_MONITOR__Alert_Project: ""
REPLICATION_MONITOR__Alert_Secret: ""
REPLICATION_MONITOR__Alert_URL: ""
REPLICATION_MONITOR__Alert_Version: ""
REPLICATION_MONITOR__Database_Endpoint: postgres://127.0.0.1:5432/pebble?sslmode=disable
REPLICATION_MONITOR__Logger_Level: DEBUG
