permissions:
  packages: write

name: build_image

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: machinefi/pebble-sequencer

jobs:
  build_image:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup docker colima on macos
        if: startsWith( matrix.os, 'macos-latest' ) == true
        run: |
          brew install docker colima
          colima start

      - uses: docker/setup-buildx-action@v2

      - name: Login to registry ${{ env.REGISTRY }}
        id: pebble-sequencer
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract docker metadata
        id: pebble-sequencer
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push images
        uses: docker/build-push-action@v4
        with:
          context: .
          platform: linux/amd64,linux/arm64
          file: cmd/sequencer/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.pebble-sequencer.outputs.tags }}
          labels: ${{ steps.pebble-sequencer.outputs.labels }}
